start_feeding:
  name: Start Feeding
  description: Start a breastfeeding session
  fields:
    side:
      name: Breast Side
      description: Which breast to start feeding from
      required: true
      selector:
        select:
          options:
            - label: Left
              value: left
            - label: Right
              value: right
    notes:
      name: Notes
      description: Optional notes about the feeding session
      selector:
        text:

stop_feeding:
  name: Stop Feeding
  description: Stop the current feeding session
  fields:
    notes:
      name: Notes
      description: Optional notes about the feeding session
      selector:
        text:

log_diaper:
  name: Log Diaper Change
  description: Log a diaper change
  fields:
    type:
      name: Diaper Type
      description: Type of diaper change
      required: true
      selector:
        select:
          options:
            - label: Pee
              value: pee
            - label: Poo
              value: poo
            - label: Both
              value: both
    notes:
      name: Notes
      description: Optional notes about the diaper change
      selector:
        text:

log_sleep_start:
  name: Log Sleep Start
  description: Log when baby starts sleeping
  fields:
    notes:
      name: Notes
      description: Optional notes about the sleep session
      selector:
        text:

log_wake_up:
  name: Log Wake Up
  description: Log when baby wakes up
  fields:
    notes:
      name: Notes
      description: Optional notes about waking up
      selector:
        text:

log_bottle_feeding:
  name: Log Bottle Feeding
  description: Log a bottle feeding session
  fields:
    amount_ml:
      name: Amount (ml)
      description: Amount of milk/formula in milliliters
      required: true
      selector:
        number:
          min: 0
          max: 500
          unit_of_measurement: ml
    notes:
      name: Notes
      description: Optional notes about the bottle feeding
      selector:
        text:

log_growth:
  name: Log Growth Measurement
  description: Log baby's growth measurements
  fields:
    weight_kg:
      name: Weight (kg)
      description: Baby's weight in kilograms
      selector:
        number:
          min: 0
          max: 20
          step: 0.01
          unit_of_measurement: kg
    height_cm:
      name: Height (cm)
      description: Baby's height in centimeters
      selector:
        number:
          min: 0
          max: 100
          step: 0.1
          unit_of_measurement: cm
    notes:
      name: Notes
      description: Optional notes about the measurement
      selector:
        text:

update_button_mapping:
  name: Update Button Mapping
  description: Add or update a button mapping configuration
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID to map
      required: true
      selector:
        entity:
          domain: [button, switch, input_button, binary_sensor]
    trigger_action:
      name: Trigger Action
      description: Specific trigger action (optional, for buttons)
      selector:
        text:
    baby_care_action:
      name: Baby Care Action
      description: The baby care action to trigger
      required: true
      selector:
        select:
          options:
            - label: Start Left Breast Feeding
              value: feeding_start_left
            - label: Start Right Breast Feeding
              value: feeding_start_right
            - label: Stop Feeding
              value: feeding_stop
            - label: Start Sleep
              value: sleep_start
            - label: Wake Up
              value: wake_up
            - label: Log Pee Diaper
              value: diaper_pee
            - label: Log Poo Diaper
              value: diaper_poo
            - label: Log Both (Pee & Poo)
              value: diaper_both

remove_button_mapping:
  name: Remove Button Mapping
  description: Remove a button mapping configuration
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID to remove mapping from
      required: true
      selector:
        entity:
          domain: [button, switch, input_button, binary_sensor]
    specific_action:
      name: Specific Action
      description: Specific action to remove (optional)
      selector:
        text:
